### ISSUE TITLE
error with homeAxis in uc2_move_positoinlist.py

### ISSUE THREAD

**Issue by ghost** [beniroquai/ImSwitchConfig#2]
@beniroquai 
The following commands in the document _uc2_move_positoinlist.py_ cause imswitch to hang:
#api.imcontrol.homeAxis(positionerName, "X")
#api.imcontrol.homeAxis(positionerName, "Y")

**Comment by beniroquai** [comment]
Fixed in https://github.com/openUC2/ImSwitch/blob/master/imswitch/imcontrol/controller/controllers/PositionerController.py#L141 due to missing control statemetn (run-in-background). However, the motor is not reporting the reach of the final destination. Would you mind showing the the result tomorrow? :)
